name: Pull Request Linter
description: A GitHub action that enforces conventional commit spec on pull requests to ensure a clean commit history.
author: Navigation
runs:
  using: composite
  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        cache: npm
    - name: Install dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: npm ci --quiet
    - name: Run PR linter
      shell: bash
      working-directory: ${{ github.action_path }}
      run: npx tsx src/main/index.ts
branding:
  icon: git-pull-request
  color: blue

