name: PR Lint Tests

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  actions: read
  checks: write
  contents: write
  pull-requests: write

jobs:
  test:
    uses: ./.github/workflows/node-tests.yml
    secrets: inherit
  run-check:
    if: ${{ github.event_name != 'push' }}
    needs: test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: ./
  success:
    needs: [test, run-check]
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Workflow successful"