name: Release

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Perform a dry run of the release thus not creating releases/tags"
        type: choice
        default: 'false'
        options:
          - 'true'
          - 'false'

permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency:
  group: release-main
  cancel-in-progress: false

jobs:
  release:
    name: Create Release
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-24.04
    outputs:
      new_release_published: ${{ steps.release.outputs.new_release_published }}
      new_release_version: ${{ steps.release.outputs.new_release_version }}
      new_release_notes: ${{ steps.release.outputs.new_release_notes }}
      new_release_major_version: ${{ steps.release.outputs.new_release_major_version }}
      new_release_minor_version: ${{ steps.release.outputs.new_release_minor_version }}
      new_release_patch_version: ${{ steps.release.outputs.new_release_patch_version }}
      last_release_version: ${{ steps.release.outputs.last_release_version }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
      - id: release
        name: Semantic Release
        uses: cycjimmy/semantic-release-action@b12c8f6015dc215fe37bc154d4ad456dd3833c90 # v6.0.0
        with:
          dry_run: ${{ inputs.dry-run }}
          extra_plugins: |
            @semantic-release/exec@7.0.2
            conventional-changelog-conventionalcommits@8.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Success summary
        if: ${{ steps.release.outputs.new_release_published == 'true' }}
        run: |
          cat <<EOF >> $GITHUB_STEP_SUMMARY
            ### :bookmark: ✅ New release created (${{ steps.release.outputs.new_release_version }})
            **Release Notes:**
            ${{ steps.release.outputs.new_release_notes }}
          EOF

  update-major-tag:
    name: Update Major Tag
    needs: release
    if: ${{ needs.release.outputs.new_release_published == 'true' && inputs.dry-run != 'true' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Source
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0

      - name: Move major tag
        env:
          TAG_NAME: v${{ needs.release.outputs.new_release_version }}
          MAJOR_TAG: v${{ needs.release.outputs.new_release_major_version }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          git fetch --tags --force
          git tag -fa "$MAJOR_TAG" "$TAG_NAME" -m "chore(release): move $MAJOR_TAG to $TAG_NAME"
          git push origin "refs/tags/$MAJOR_TAG" --force
